Algoritmo "TABELA DA VERDADE I"

// Data atual  : 01/05/2023
Var
i,j:inteiro

Inicio

   Escreval("Escreva sua idade")
   leia(i)
   
   Escreval("Escreva sua idade")
   leia(j)

se (i >18 ) E (j>18) entao
   Escreval("Ambos são maior de idade")
senao
   se (i >18 ) E (j<18) entao
      Escreval("O segundo é menor de idade")
   senao
        Escreval("O primeiro é menor de idade")
   fimse
fimse
Fimalgoritmo